name: Trigger auto deployment for mkheck-ppp-ca-gh

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mkheck-ppp-ca-gh-AutoDeployTrigger-f6fcd8e1-c66e-4f44-aff5-06ffa6bfe166.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MKHECKPPPCAGH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MKHECKPPPCAGH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MKHECKPPPCAGH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: mkheckcontainerregistry.azurecr.io
          registryUsername: ${{ secrets.MKHECKPPPCAGH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MKHECKPPPCAGH_REGISTRY_PASSWORD }}
          containerAppName: mkheck-ppp-ca-gh
          resourceGroup: mkheck-7287-rg
          imageToBuild: mkheckcontainerregistry.azurecr.io/mkheck-ppp-ca-gh:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


